version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

  flask-api:
    build: ./flask-api
    ports:
      - "5000:5000"
    environment:
      - KAFKA_SERVER=kafka:9092
    networks:
      - kafka-network
    volumes:
      - shared-data:/data

  producer:
    build: ./producer
    command: ["python", "producer.py"]
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER=kafka:9092
    networks:
      - kafka-network

  consumer:
    build: ./consumer
    command: ["python", "consumer.py"]
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER=kafka:9092
    volumes:
      - shared-data:/data
    networks:
      - kafka-network

volumes:
  shared-data:
    driver: local

networks:
  kafka-network:
    driver: bridge
